import Head from "next/head";
import Image from "next/image";
// import { Navbar } from "../components/Navbar.jsx";
import { Hero } from "../components/Hero.jsx";
import { Skills } from "../components/Skills.jsx";
import { AboutMe } from "../components/AboutMe.jsx";
// import { Portfolio } from "../components/Portfolio.jsx";
// import { WorkTogether } from "../components/WorkTogether.jsx";
// import { ContactMe } from "../components/ContactMe.jsx";
// import { Footer } from "../components/Footer.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Raquel Pfeifle | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2016%2016%22%3E%3Ctext%20x%3D%220%22%20y%3D%2212%22%20font-size%3D%2215%22%3E%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%92%BB%3C%2Ftext%3E%3C%2Fsvg%3E
          "
        />
      </Head>
      {/* <Navbar /> */}
      <Hero />
      {/* <Skills /> */}
      <AboutMe />
    </>
  );
}
