import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { Hero } from "../components/Hero.jsx";
import { AboutMe } from "../components/AboutMe.jsx";
import { Skills } from "../components/Skills.jsx";
import { ProjectCard } from "../components/portfolioSection/ProjectCard.jsx";
import { WorkWithMe } from "../components/WorkWithMe.jsx";
import { Contact } from "../components/Contact.jsx";
import { Footer } from "../components/Footer.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Raquel Pfeifle | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2016%2016%22%3E%3Ctext%20x%3D%220%22%20y%3D%2212%22%20font-size%3D%2215%22%3E%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%92%BB%3C%2Ftext%3E%3C%2Fsvg%3E
          "
        />
      </Head>
      <Navbar />
      <Hero />
      <AboutMe />
      <Skills />
      <section id="portfolio" className="container">
        <h2 className="underlineEffect pb-6">Projects</h2>
        <ProjectCard
          projectName="Tripaholics"
          technologies={[
            "Python",
            "JavaScript",
            "Bootstrap",
            "Jinja2",
            "Flask",
            "PostgreSQL",
            "SQLAlchemy",
            "Twilio's SendGrid API",
            "Unsplash Images API",
            "Swiper API",
            "Google Maps API",
          ]}
          description="Description of what was done with the project. Lorem ipsum dolor sit amet consectetur adipisicing elit. In itaque sequi natus cupiditate voluptates quas voluptatibus temporibus, incidunt, perspiciatis, corrupti unde? Sit distinctio veritatis eaque quae dolor velit alias reprehenderit?"
          caseStudyLink="https://"
          demoLink="https://www.youtube.com/watch?v=c5srainYwKA"
          codeLink="https://github.com/rdpfeifle/Travel-web-app"
          imageSrc="/assets/images/coming-soon.png"
          imageAlt="Tripaholics Mockup Image"
        />
        <ProjectCard
          projectName="Portfolio Website"
          technologies={["Next.js", "React", "Tailwind CSS"]}
          description="Description of what was done with the project. Lorem ipsum dolor sit amet consectetur adipisicing elit. In itaque sequi natus cupiditate voluptates quas voluptatibus temporibus, incidunt, perspiciatis, corrupti unde? Sit distinctio veritatis eaque quae dolor velit alias reprehenderit?"
          caseStudyLink="https://"
          demoLink="https://"
          codeLink="https://github.com/rdpfeifle/portfolio_nextjs"
          imageSrc="/assets/images/coming-soon.png"
          imageAlt="Portfolio Mockup Image"
        />
        <ProjectCard
          projectName="E-commerce"
          technologies={["Next.js", "React", "TypeScript", "Tailwind CSS"]}
          description="Description of what was done with the project. Lorem ipsum dolor sit amet consectetur adipisicing elit. In itaque sequi natus cupiditate voluptates quas voluptatibus temporibus, incidunt, perspiciatis, corrupti unde? Sit distinctio veritatis eaque quae dolor velit alias reprehenderit?"
          caseStudyLink="https://"
          // demoLink="https://"
          codeLink="https://"
          liveLink="https://"
          imageSrc="/assets/images/coming-soon.png"
          imageAlt="Project Mockup Image"
        />
      </section>
      <WorkWithMe />
      <Contact />
      <Footer />
    </>
  );
}
